--- 
abstract: A key indexable Cache::Memcached wrapper
author: Koichi Taniguchi <taniguchi@livedoor.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Cache-Memcached-Indexable
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cache::Memcached: 1.17
  Digest::SHA1: 0
  UNIVERSAL::require: 0.1
version: 0.03
